version: '3'
services: 
  
  node:
    build: ./Debian
    tty: true
    networks: 
      - db

  mongos:
    build: ./Debian
    tty: true
    networks: 
      - db

  config:
    build: ./Debian
    tty: true
    networks: 
      - db

networks: 
  db:
    ipam:
      config:
        - subnet: 10.10.10.0/24

