---
- name: Setting replica
  lineinfile: 
    dest: /etc/mongodb.conf
    line: "{{ item }}"
  with_items:
    - "port = 27017"
    - "replSet = rs0"
    - "fork = true"

- name: Replacing bind_ip 
  replace: 
    dest: /etc/mongodb.conf
    regexp: "^bind_ip = 127.0.0.1"
    replace: "bind_ip = {{ansible_default_ipv4.address}}"
  
- debug: 
    msg: "{{ansible_default_ipv4.address}}"
